### ISSUE TITLE
`gorouter` job fails when access-log streaming is enabled

### ISSUE THREAD

**Issue by x6j8x** [cloudfoundry/routing-release#118]
cf-deployment 3.2.0 // routing-release 0.180.0

## Issue

We have router access-log syslog streaming enabled in our environment. After trying to upgrade to cf-deployment 3.2.0 `gorouter` fails with the following error message:

```
{"log_level":3,"timestamp":1534164239.201265,"message":"error-creating-syslog-writer","source":"vcap.gorouter.access-log","data":{"error":"Unix syslog delivery error"}}
{"log_level":6,"timestamp":1534164239.2012856,"message":"error-creating-access-logger","source":"vcap.gorouter","data":{"error":"Unix syslog delivery error"}}
```

It shouldn't be relevant for the issue, but we have `syslog-forwarder` from `syslog-release` collocated on the VM via BOSH runtime-config. 

Could this be connected to the `bpm` conversion?

Best,

Sascha

**Comment by shubhaat** [comment]
Hi @x6j8x , 

Thanks for reporting this, I could reproduce this and will prioritize this for further investigation. 

Regards, 
Shubha

**Comment by shubhaat** [comment]
@x6j8x 

To take the conversation to the issue for public view, as mentioned yes, this is related to BPM. Since BPM does not have automatic log forwarding, this just stops working when the Gorouter uses BPM (follow conversation [here](https://github.com/cloudfoundry-incubator/bpm-release/issues/82). 

BPM recommends using something like the [syslog release](https://github.com/cloudfoundry/syslog-release) to send your logs from the machine to an external log aggregator and store. Though syslog forwarding does not work exactly the same way that this feature is implemented in the Gorouter. The files are still written to disk, and might grow to about ~50MB. 

As I understand, the reason you prefer streaming the logs, is because you all saw your disks filling up previously. With some of the recent fixes in syslog release, I believe log volumes should now be reduced, and this problem might have been mitigated. Though it is still possible that disks still fill up. 

Would you be open to disabling `router.enable_access_log_streaming` and giving it a try?

We are leaning towards deprecating this flag, and sticking with the more standard implementation for log forwarding as provided by syslog release. 

Regards, 
Shubha

**Comment by x6j8x** [comment]
@shubhaat Thanks for the detailed answer. 

We've deactivated `router.enable_access_log_streaming` to unblock our pipeline.

One thing though... As logrotation only happens once per hour the access logs files can grow much larger then 50MB. 

I guess it comes down to the question on what's more important _availability_ or _traceability_. 

If the latter is most important the current behaviour works fine. It will ultimately prevent the router from handling requests when the operator provisioned to litte ephemeral disk space and  the disk fills up with access logs. So no un-logged request can reach your apps. 

If the former is more important I guess rotation based on absolute disk space used would be a better fit than based on time (once per hour regardless how large the files grow). But I don't know how feasible that is.

**Comment by shubhaat** [comment]
That sounds reasonable. I am following up with the BOSH teams and the syslog release teams to discuss rotating log files based on size. I'll keep this issue open, and keep this updated based on the conversations.

**Comment by shalako** [comment]
Hi @x6j8x 
Our short term plan is to restore support for `router.enable_access_log_streaming`, by which we handle streaming of access logs to a syslog consumer within routing-release without writing to disk; we've found a way around the BPM constraint and are working on this now.

In the mid- to long-term, we'd like to remove responsibility for syslog from individual component releases, in favor of syslog-release, as this guarantees a consistent log format across the platform. However, syslog-release necessarily requires that logs are written to disk in order to be streamed. The means we would have to rely on increased disk and/or increased frequency of logrotate filesize checking.

Could you share with us the volume of access logs each your highest traffic gorouter instance generates within some time window (sec or min), and let us know whether increasing disk size would be viable for you?

We've spoken with @dpb587-pivotal and @jfmyers9 on the BOSH team, who have suggested we could enhance https://github.com/cloudfoundry/os-conf-release to support overriding the cron for logrotate, but are hesitant about modifying stemcell defaults. They are hoping that increasing disk size is a viable solution to prevent disks filling up. 

 /cc @mfine30, @anEXPer

**Comment by dpb587-pivotal** [comment]
@x6j8x the default stemcell configuration should be rotating logs [every 15m](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/741f485675f13ec3cda19d375b8f30b1aa1c584c/bosh-stemcell/spec/support/stemcell_shared_examples.rb#L96-L97), not once an hour. Can you confirm in your environment what your effective cron/rotation policy is?

To clarify a bit, BOSH is hesitant about modifying stemcell defaults because historically log rotation every 15m has provided a healthy balance between disk requirements and expected usage. If we have more raw data about those factors in various environments, we can certainly re-evaluate. Feel free to provide more details to help in this discussion.

**Comment by shalako** [comment]
@x6j8x I've validated that deploys succeed now when `router.enable_access_log_streaming: true`. However, it also looks like `router.enable_access_log_streaming: false` doesn't prevent syslog streaming. I believe this may be because syslog-release will stream logs if they are written to disk.

I'm wondering whether we can get rid of `router.enable_access_log_streaming`, and rely on the presence of syslog-release to determine whether syslogs are streamed.

**Comment by x6j8x** [comment]
@shalako I‘m all for it as the property now suggests functionality that simply isn‘t there anymore. 

Regarding the log rotation issue we now simply allocated 10x he storage we would normally need to account for unforseen traffic spikes.

**Comment by adobley** [comment]
@x6j8x The related story to resolve this https://www.pivotaltracker.com/n/projects/1358110/stories/159756469 is in the routing-release as of [0.181.0](https://github.com/cloudfoundry/routing-release/releases/tag/0.181.0). Does this look like it resolves this issue for you?
