### ISSUE TITLE
lib/pq library is deprecated

### ISSUE THREAD

**Issue by mdelillo** [cloudfoundry/routing-release#164]
## Issue

According to their [README](https://github.com/lib/pq/blob/f3b22b2cad9e4567803b7ffd9853b8acda021438/README.md#status), the lib/pq library is in maintenance mode. We should instead use [pgx](https://github.com/jackc/pgx).

Diego recently did this [here](https://github.com/cloudfoundry/diego-release/pull/511).

**Comment by mcwumbly** [comment]
text from `lib/pq` readme:

> This package is effectively in maintenance mode and is not actively developed. Small patches and features are only rarely reviewed and merged. We recommend using [pgx](https://github.com/jackc/pgx) which is actively maintained.

also (via https://github.com/cloudfoundry/diego-release/pull/511#issuecomment-626973971), notably, this prevented Diego from removing lib/pq completely, since they also depend on `routing-api`:

> We still had to keep the submodule because routing-api depends on the deprecated library. Opened cloudfoundry/routing-release#164 issue for future reference.

@mdelillo I'm going to label this "scheduled" as well as "help wanted" - we'll pick it up at some point, but if someone out there wants to submit pull requests to resolve this in advance, we would welcome that too.

**Comment by mcwumbly** [comment]
removing scheduled label from this to better reflect its current priority... if it gets closer to the top of your list again, we'll add it back.

but for now, it's up for grabs!

**Comment by moleske** [comment]
For giggles I tried deleting the `lib/pq` submodule and compiling just to see what breaks.  It turns out [gorm](https://github.com/jinzhu/gorm/blob/1558522aaaac6aec4e7de3916b68e3e50507e09b/dialects/postgres/postgres.go#L7) has a dependency on `lib/pq` since the build failed to compile on tcp router

```shell
Failed to compile cf-tcp-router:

../../github.com/jinzhu/gorm/dialects/postgres/postgres.go:7:2: cannot find package "github.com/lib/pq" in any of:
	/usr/local/go/src/github.com/lib/pq (from $GOROOT)
	/routing-release/src/github.com/lib/pq (from $GOPATH)
../../github.com/jinzhu/gorm/dialects/postgres/postgres.go:8:2: cannot find package "github.com/lib/pq/hstore" in any of:
	/usr/local/go/src/github.com/lib/pq/hstore (from $GOROOT)
	/routing-release/src/github.com/lib/pq/hstore (from $GOPATH)
```

There is a recommended replacement for pq (pgx), but no mention of what to do when pq is a transitive dependencies.  I don't have thoughts on this since not super familiar with the code

**Comment by mcwumbly** [comment]
Looks like maybe we just need to update `gorm` to the latest version... haven't dug deep, but I think they may have switched underlying libraries now: https://github.com/go-gorm/gorm/pull/1712

**Comment by MarcPaquette** [comment]
Hi @mdelillo, 

We're going to stick with using lib/pq until it is no longer maintained.  If this changes will be be looking at other options.

Thanks for bringing this to our attention!
