### ISSUE TITLE
vcap_id cookie is sent without SameSite value when JSESSION id is not set again

### ISSUE THREAD

**Issue by stefanlay** [cloudfoundry/routing-release#178]
No

## Issue

Since https://github.com/cloudfoundry/gorouter/pull/262 the gorouter sets the "SameSite" value of the __VCAP_ID__ cookie based on the value of the JSESSIONID cookie that came back from the app.

With https://github.com/cloudfoundry/gorouter/commit/126cf4d8c7a0a1c2e7de7457496969c81f367cfc as fix for [Issue #170](https://github.com/cloudfoundry/routing-release/issues/170) a __VCAP_ID__ cookie is sent even if the app does not set the JSESSION id explicitly on the response. In that case, the __VCAP_ID__ cookie does not contain the "SameSite" value. Clients relying on the "SameSite" value are broken. 

## Affected Versions

routing release since https://github.com/cloudfoundry/routing-release/releases/tag/0.202.0
## Context

 
 

See above

## Steps to Reproduce

1. Push an app which sets a JSessionId on the first request, but not on follow-up requests in the same session
2. Curl the app
`curl -b cookie -c cookie -i URL`
3. Curl the app again
`curl -b cookie -c cookie -i URL`
## Expected result

First Response:
`Set-Cookie: JSESSIONID=test; Expires=Thu, 06 Aug 2020 10:40:38 GMT; SameSite=Lax
Set-Cookie: __VCAP_ID__=8d157840-5a42-41cd-7fb6-f84f; Path=/; HttpOnly; Secure; SameSite=Lax`

Second Response:
Either
`Set-Cookie: __VCAP_ID__=8d157840-5a42-41cd-7fb6-f84f; Path=/; HttpOnly; Secure; SameSite=Lax`

or no __VCAP_ID__ cookie

## Current result

First response:
`Set-Cookie: JSESSIONID=test; Expires=Thu, 06 Aug 2020 10:40:38 GMT; SameSite=Lax
Set-Cookie: __VCAP_ID__=8d157840-5a42-41cd-7fb6-f84f; Path=/; HttpOnly; Secure; SameSite=Lax`

Second response:
`Set-Cookie: __VCAP_ID__=8d157840-5a42-41cd-7fb6-f84f; Path=/; HttpOnly; Secure`

**Comment by ameowlia** [comment]
Hi @stefanlay, 

Thank you for opening this issue and including the commit responsible for causing this bug. Our team will look into this soon. However, for the fastest fix I recommend submitting a PR. 

To help us prioritize can you describe what problems this causes the end user? 

Thanks, 
Amelia, CF Networking Team Member

**Comment by stefanlay** [comment]
Hi @ameowlia,

thanks for your response. We were looking into creating a PR, but found it non-trivial to fix it without breaking the fix for Issue #170. 

One big customer of us created a ticket with the following messages:

"We embed <the browser client> in our Excel add-in. As the cookie is blocked the customer can't use our add-in.
The only workaround is to disable the corresponding security settings in Chrome. Many customers are not willing to do that."

"it is currently embedded as an Iframe to many products in SAP including ... and .. and many customers also embed ... in their reports."

If I understand correctly, setting the JSESSION id cookie in the App on every request would mitigate the issue. Is there any recommendation about that in general? The documentation [1] is not explicit on that. Do you have experience how typical runtimes like spring or node handle the jsession id?

Thanks,
Stefan

[1] https://docs.cloudfoundry.org/concepts/http-routing.html#sessions

**Comment by thomas-kaltenbach** [comment]
Hi all,

because more and more problems are reported in our landscapes we investigated in this topic. The urgency grows day by day.

In our case the easiest would be to revert the change of the issue #170 , but I had a deeper look into the problem and I was wondering if that might be a solution.

**Proposal**
The RouteServiceURL is  only filled if a RouteService is involved. So I thought it might be possible to change the coding [here](https://github.com/cloudfoundry/gorouter/blob/35c737bc811ed604fbbb6b10d487b2d0940162ca/proxy/round_tripper/proxy_round_tripper.go#L213) to the followed:		
```
	if res != nil && endpoint.PrivateInstanceId != "" {
		var isRouteService = reqInfo.RouteServiceURL != nil
		setupStickySession(
			res, endpoint, stickyEndpointID, rt.secureCookies,
			reqInfo.RoutePool.ContextPath(), rt.stickySessionCookieNames,
			isRouteService, // <-- additional property
		)
	}
```
And in the method setupStikySession we could change the coding [here](https://github.com/cloudfoundry/gorouter/blob/35c737bc811ed604fbbb6b10d487b2d0940162ca/proxy/round_tripper/proxy_round_tripper.go#L306) to the followed:
```
	var sticky bool
	if isRouteService {
		sticky = originalEndpointId != ""
	} else {
		sticky = originalEndpointId != "" && originalEndpointId != endpoint.PrivateInstanceId
	}
```
So hopefully the gorouter behave for all applications without an additional RouteService as before #170 and the RouteService and Sticky Sessions should be still supported.

We would be happy if we could get feedback quickly and could solve the problem.

Thanks and regards,
Thomas

**Comment by jrussett** [comment]
Hi @stefanlay and @thomas-kaltenbach,

Thank you for opening and engaging with this issue.

## Reverting the work for #170
We recognize the fix for #170 is problematic so we decided to revert the original fix that we had:
- https://github.com/cloudfoundry/gorouter/commit/27aa7375601ac0211d8167fc730a90142b0cdf9f
- https://github.com/cloudfoundry/routing-release/commit/1c47a98b699dcc66ba6c12a97dd0124f89badd8d

We have also reopened GitHub Issue #170 and will begin the process of finalizing and releasing a new routing release soon.

## Our Ask
Our ask from you now is to please update Issue #170 with any additional context that y'all have for the next time that someone takes a stab at an implementation of that feature.

Thanks!
@jrussett and @mcwumbly

**Comment by domdom82** [comment]
Just to add my 2 cents to this problem (since I provided the "samesite" fix for VCAP_ID originally in https://github.com/cloudfoundry/gorouter/pull/262): I wonder how this would even work if JSESSIONID is not set by gorouter. The code currently takes the value of "samesite" from the JSESSIONID cookie and applies the same value to VCAP_ID. There is no way to obtain the correct setting from anywhere if the JSESSIONID is not set at all.

I agree with @a09-capf in https://github.com/cloudfoundry/routing-release/issues/170 that gorouter should not set VCAP_ID regardless. We need to find a better solution to fix routing problems with in-between route services or proxies.

I wonder if it would make sense to treat route intermediaries in a special endpoint list so that we don't run the same code as with apps and the logic that applies VCAP_ID will never run on them. That would avoid accidentally setting VCAP_ID to an intermediary endpoint.

**Comment by mcwumbly** [comment]
> I wonder if it would make sense to treat route intermediaries in a special endpoint list so that we don't run the same code as with apps and the logic that applies VCAP_ID will never run on them. That would avoid accidentally setting VCAP_ID to an intermediary endpoint.

Note there is a current workaround for the feature requested in #170: have the _app_ always set `JSESSIONID`.
