### ISSUE TITLE
Enable map-route to more than one space to simplify application configurations and service discovery for blue / green scenarios 

### ISSUE THREAD

**Issue by pauldavidgilligan** [cloudfoundry/routing-release#190]
## Is this a security vulnerability?

No

## Issue

The **CF-RR** design https://docs.cloudfoundry.org/devguide/deploy-apps/blue-green.html and the gorouter do not currently detail / support routing across spaces which causes the following drawbacks when using microservices that depend on service discovery and or a configuration server.

1. Consider application app-x which has a manifest that lists a set of services that is depends on, e.g. app-y, app-z. Under the CF-RR design we deploy app-x-green and so we have to modify the manifest to list app-y-green, app-z-green.
1. Consider service discovery for a spring boot application; deployed as app-x-green and spring.application.name=app-x-green then by default eureka services discovery will register the service as app-x-green, now the configuration paths in the backend config service must also support app-x-green.yml you will then possibly have to maintain app-x.yml, app-x-green.yml and app-x-blue.yml
1. If you spent time and money working on UAT how can you we also guarantee that the re-named and changed configurations match the approved one from UAT? 

## Affected Versions

Current release of licensed PCF paas.

## Context

We have tested

1. Deployments of the CF-RR blue/green design to a demo space called prod to get a full end to end picture of the challenges we are facing.

1. Deployments of a more direct test of blue/green to 2 demo spaces called Blue & Green leads to an approx 7sec outage of service due to the switching of the route mapping.

## Traffic Diagram 

 client   ----> go router  ---> app-x-green ---> config server path=/app-x-green/application.yml                                                                    

### CF-RR
```
DT deploy blue version 1
========================

cf target -o Demo -s Prod
cf push Blue --no-route
cf create-route sandbox.example.com --hostname demo-time
cf map-route Blue sandbox.example.com --hostname demo-time
service instance url = https://demo-time.sandbox.example.com/

space   host        domain                   port   path   protocol   apps
Prod    demo-time   sandbox.example.com                 http       Blue

ST production service version 1 
===============================
production service available on https://demo-time.sandbox.example.com/

DT deploy green version 2
=========================
cf push Green --no-route
cf create-route sandbox.example.com --hostname demo-time-temp
cf map-route Green sandbox.example.com --hostname demo-time-temp
service instance url = https://demo-time-temp.sandbox.example.com/

space   host             domain                   port   path   protocol   apps
Prod    demo-time        sandbox.example.com                 http       Blue
Prod    demo-time-temp   sandbox.example.com                 http       Green

ST production service version 2
===============================
cf map-route Green sandbox.example.com --hostname demo-time

space   host             domain                   port   path   protocol   apps
Prod    demo-time        sandbox.example.com                 http       Blue, Green
Prod    demo-time-temp   sandbox.example.com                 http       Green

cf unmap-route Blue sandbox.example.com --hostname demo-time

space   host             domain                   port   path   protocol   apps
Prod    demo-time        sandbox.example.com                 http       Green
Prod    demo-time-temp   sandbox.example.com                 http       Green

cf unmap-route Green sandbox.example.com --hostname demo-time-temp
cf delete-route sandbox.example.com --hostname demo-time-temp

space   host        domain                   port   path   protocol   apps
Prod    demo-time   sandbox.example.com                 http       Green

RT production service version 1
===============================
cf map-route Blue sandbox.example.com --hostname demo-time

space   host        domain                   port   path   protocol   apps
Prod    demo-time   sandbox.example.com                 http       Green, Blue

cf unmap-route Green sandbox.example.com --hostname demo-time

space   host        domain                   port   path   protocol   apps
Prod    demo-time   sandbox.example.com                 http       Blue
```

### 2 separate spaces 

```
DT deploy blue version 1
========================
cf target -o Demo -s Blue
cf push --no-route
cf create-route sandbox.example.com --hostname blue-cf-ex-php-info
cf map-route cf-ex-php-info sandbox.example.com --hostname blue-cf-ex-php-info
service instance url = https://blue-cf-ex-php-info.sandbox.example.com/

ST production service version 1 
===============================
cf map-route cf-ex-php-info sandbox.example.com --hostname myapp
production service available on https://myapp.sandbox.example.com/

DT deploy green version 2
=========================
cf target -o Demo -s Green
cf push --no-route
cf create-route sandbox.example.com --hostname green-cf-ex-php-info
cf map-route cf-ex-php-info sandbox.example.com --hostname green-cf-ex-php-info
service instance url = https://green-cf-ex-php-info.sandbox.example.com/

ST production service version 2
===============================
cf target -o Demo -s Blue
cf unmap-route cf-ex-php-info sandbox.example.com --hostname myapp
cf delete-route sandbox.example.com --hostname myapp

(service unreachable)

cf target -o Demo -s Green
cf map-route cf-ex-php-info sandbox.example.com --hostname myapp

(service reachable)

RT production service version 1
===============================
cf target -o Demo -s Green
cf unmap-route cf-ex-php-info sandbox.example.com --hostname myapp
cf delete-route sandbox.example.com --hostname myapp

(service unreachable)

cf target -o Demo -s Blue
cf map-route cf-ex-php-info sandbox.example.com --hostname myapp

(service reachable)
```

## Expected result

To be able to map routes across one or more spaces.

## Current result

```
cf map-route cf-ex-php-info sandbox.example.com --hostname myapp
Routes cannot be mapped to destinations in different spaces.FAILED
```

**Comment by ameowlia** [comment]
Hi @pauldavidgilligan , 

We don't allow mapping-routes across spaces because we don't want people to _accidentally_ map a route to two different apps. Imagine the following scenario:

1. Space1-Dev pushes an app with a generic name like "test" or "frontend" or "backend" or "app" or "api". For this example I will use "backend".
1. Users are happily able to access the app at `backend.my-domain.com`
1. Later, space2-Dev pushes an app also called "backend". 
1. Space2-Dev has no insight into space1. Space2-Dev does not have the permissions to see apps or routes for other spaces. 
1. Space2-Dev maps her app "backend" to the route `backend.my-domain.com`
1. Users trying to access the backend app in space1 are now redirected to the backend app in space2 sometimes.
1. Space1-Dev hears reports that her app is failing sometimes, but there is no info in her app logs. She doesn't have permissions to see other apps or routes. 
1. When space1-dev finally determines that her `backend.my-domain.com` route is failing because it is sometimes being routed to another app she has to reach out to a CF admin  who _can_ look up all routes and all apps.
1. At this point the CF admin will have to determine if things are failing because of user error or because the gorouter is messing up .
1. They work together and realize that space2 "backend" app is to blame. 

Not an ideal situation. 

As you noted, there is a simple workaround for your problem: both apps must be in the same space. Though I understand this limitation can be frustrating occasionally, I personally think it is an okay trade-off to make to ensure that no one runs into the situation above.

Before I close this issue, I would like to give you the chance to: 
* explain the pain you are feeling in more detail and why requiring that the two apps be in the same space is not acceptable
* propose a way to prevent the above situation. 

Thanks, 
Amelia ❄️

**Comment by pauldavidgilligan** [comment]
Hi Amelia,

That is an interesting scenario so the real issue above is the dev users ability to query route information across different spaces due to access controls, having access controls to spaces is a good thing of cause. 

I would have though the solution to the above is simple given that each space is part of an organization we can provide  an organization level role that would allow dev users to query routes (read only) across all spaces for a given organization.

Providing dev users the ability to clearly "see" api routes I think is good thing and is probably provided by other api routing software also.

This would avoid confusion is the scenario you point out above but even so I think that scenario is much less of an issue than trying to maintain 100s of yaml configuration files if you have 50 micro services with 3 configuration yaml files for each then we are taking about maintaining 150 yaml files per release instead of 50.

From an automation perspective we would like to use the same process that we use for UAT to deploy to Production any deviation from this deployment process invalidates UAT. For example we can deploy 10 micro services to UAT give this release to users to test over several weeks and then when approved release to production into a space called "Prod". All is well and everyone is happy. Developers have made changes as required to application code AS WELL as configuration items under this release.

BUT if we are using blue / green in a single space then we have to rename each of the 10 applications and potentially their respective yaml configuration files deviating from the standard UAT release processes. I did some risk analysis:

The current production setup uses a mixed blue / green deployment with in the same cloud foundry space and this poses a risk in that:

- The deployment process will be different between UAT & Live due to the renaming of applications and this might invalidate the UAT approvals.

- Confusion and mistakes might be made in understanding which color is live.

- The is a risk that you intended to change blue but accidently change green as you always have to logon to a common Prod space.

- There is a risk that the colours will mixed in the scenario that app 0101 works in blue but not green and the app 0102 works in green but not in blue.

**Comment by pauldavidgilligan** [comment]
Another solution would be --force option.

`cf map-route cf-ex-php-info sandbox.example.com --hostname myapp --force`

This would place to responsibility on the developer to understand the implications of creating routes across multiple spaces.

**Comment by maxim-hansen** [comment]
Hi!

I think the `--force` flag is a good and clean interface.

The requirement would be that to use the `--force` flag you will need to fulfill **at least one** of following requirements (just a suggestion):
- Be at least a Space Developer **in all spaces where the route is already present**
- Be an Org Manager in all spaces affected by your `--force` flag

Because the GoRouter "sees all", this is sort of just an extension of the existing logic, since the GoRouter today already has checks to verify if the route already exists in another space or not.

So what we're basically saying is that as long as you have the required permissions, we treat the above check more as a warning, and you can choose to override it using `--force`, again, assuming you have the permissions needed.

_**Disclaimer**: I work at the same company as @pauldavidgilligan_ 🙂

**Comment by maxim-hansen** [comment]
Also, as a side note to the possibilities this opens up beyond Blue/Green deployments, we've also seen the following requests from some of our customers:

> We would like to run the same application on both on-prem and Azure, and be able to load-balance between the two to see how the Azure application behaves with partial load.

By allowing routes to be assigned across spaces, we open up the possibility to use the same application route across multiple Isolation Segments. And with a multi-homed BOSH that is connected to several IaaS's, we can spin up Diego Cells in different Isolation Segments, which then run on different clouds.  Since Isolation Segments can be assigned to Spaces, we can thus have something like a `vSphere Space` and an `Azure Space`, essentially allowing us to deploy our apps to different clouds!

Then you just have a "primary" deployment that contains your GoRouters (which are allowed to route between Isolation Segments), and when combined with the feature requested here, you now can have a multi-cloud routing layer!

This allows for seamless transitions between clouds, which is particularly attractive for customers looking at moving away from their on-prem deployments, and more over to pure "Cloud Native" applications, but who aren't quite ready to do it in a "Big Bang" type of fashion, and want that cozy feeling of being able to just disable some routing and be "back to normal".

Visually, the whole thing would look something like this:
![image](https://user-images.githubusercontent.com/264774/102144215-614d3180-3e65-11eb-95f9-7bca6db5fdee.png)

**Comment by ameowlia** [comment]
Hi @maximhan and @pauldavidgilligan, 

I have to say, I'm impressed. This is the best design option I've seen for this and I find the explanation in @maximhan 's latest comment very compelling. Despite this being about routes and routing, I think the "same space" restriction is in cloud controller not gorouter, which means there would need to be changes at the very least in the CLI and in capi-release. 

Since this is a cross component issue, I suggest writing up an identical issue in the cf-deployment repo and then link to this issue there. That is a good place to add issues that are for cloud foundry as a whole (even if none of the work actually needs to happen in that repo. Managing distributed systems is hard!)

**_I_** am happy with this design and would be happy if you wanted to PR this in. However, I am only involved in the routing/networking domain, so I suggest asking for design input on the cf-deployment issue and seeing what others think. 

I will also bring this up to my leadership so they know about this ask and the reasoning behind it, but I don't want to get your hopes up for prioritization. 

Thanks, 
Amelia

**Comment by pauldavidgilligan** [comment]
Perfect thanks these additional features will would provide us with a lot of flexibility going forward.

**Comment by pauldavidgilligan** [comment]
@maximhan could you please promote the design you have here to cf-deployment 💯

**Comment by pauldavidgilligan** [comment]
To get round **_this major limitation_** with the gorouters ability to handle more than one space I have had to develop an API to enable us to delivery blue / green applications safely.

**Comment by AJ-72** [comment]
@pauldavidgilligan Do you have plans to opensource the API you developed? I am also stuck at the same problem.

**Comment by MarcPaquette** [comment]
I'm going to close out this issue as stale. Feel free to reopen if there's any disagreement.
