### ISSUE TITLE
Gorouter: Replacement of transfer-encoding header with content-length header

### ISSUE THREAD

**Issue by Soha-Albaghdady** [cloudfoundry/routing-release#208]
## Issue

Gorouter no longer replace `Transfer-Encoding` header with the `Content-Length` header.

## Affected Versions

0.214.0, 0.215.0 and 0.216.0
## Context

We have noticed that in v0.213.0 release gorouter used to replace the `Transfer-encoding` header with the `Content-Length` header for a response coming from a server having `Transfer-encoding: 'chunked'` set. In release v0.214.0  and up to v0.216.0 the header is no longer replaced and the response reaches the client with the Transfer-encoding header set.

The change in the behaviour lead to some requests failing due to the Gorouter error `"error":"net/http: HTTP/1.x transport connection broken: too many transfer encodings"` for apps that doesn't check for headers before adding the transfer-encoding header.

We believe that the change in the behaviour has resulted from the upgrade of the golang version.

 
 

## Steps to Reproduce

Deploy a simple server cf app that returns a response with transfer-encoding header set to chunked. Send a request to the app and check the headers returned in the request.  
## Expected result

The response is returned with the 'Content-Length' header with the size of the returned message body

## Current result

The response is returned with the 'Transfer-Encoding' header.

**Comment by pusherofbrooms** [comment]
We are experiencing this as well with our upgrade from routing-release v0.213.0 to v0.216.0 . Sadly, some of our developers decided to implement an embedded http library which doesn't support chunked `Transfer-Encoding`.

In the 43 commits from v0.213.0 to v0.216.0, I don't see any direct changes to `Transfer-Encoding` behavior. My suspicion is that the underlying go upgrades caused the issue. I'm struggling to find the specific change amongst the thousands of commits in golang. The release notes do note some behavior changes in `Transfer-Encoding` but not specifically this change.

**Comment by kelvin-j-li** [comment]
We have the same issue when upgrading from TAS-2.11.0 (routing release 0.211.0) to TAS-2.11.6 (routing release 0.224.0).

The code changes/solution provided here (https://community.pivotal.io/s/article/Application-Chunked-Error?language=en_US) can be used to work around the issue:

`Situation #3 above, can be mitigated by not directly returning ResponseEntity objects from RestTemplate.exchange. You need to first remove the transfer-encoding header, if it's present. You could directly modify that object in your Controller before returning it, but that could get repetitive across many methods and many controllers. A less invasive way of doing this would be with a RestTemplate interceptor.`

**Comment by geofffranks** [comment]
@pusherofbrooms This change in behavior is a result of https://github.com/golang/go/commit/ca3c0df1f8e07337ba4048b191bf905118ebe251 (thanks @ameowlia!), present in golang 1.16.x but not golang 1.15.x. 

In your case it sounds like the clients don't support chunked encoding, but are talking to a service that responds with chunked encoding, and due to an unconventional behavior in golang, things worked? Is it possible to have the clients either support chunked encoding, or update the apps on CF to disallow chunking?

**Comment by geofffranks** [comment]
It does not look like we will be making any changes in the near future to gorouter related to this, so I'm going to summarize the known symptoms related to this, potential solutions, and close this out.

- Apps that proxy requests to backend apps running on CF that are copying all headers across, rather than ignoring the [hop-by-hop headers](https://datatracker.ietf.org/doc/html/rfc2616#section-13.5.1). If a proxied request was previously being converted from chunk-encoding to a content-length based response, this can result in multiple transfer-encoding headers, which triggers errors.
  - **Solution:** do not copy hop-by-hop headers in proxy apps
- App consumers which do not support chunk-encoding, when the app sends data using chunked-encoding.
  - **Solution:** enable chunk-encoding support on the app-consumer side, or disable it on the app itself.
- Apps now receiving a "premature end of chunk coded message" error, [for example if using jersey < 2.9](https://github.com/eclipse-ee4j/jersey/issues/3629)
  - **Solution:** Update jersey, or other http client libraries, and ensure your app is processing http responses in a thread-safe manner.
