### ISSUE TITLE
Uneven load balancing when using a route-service.

### ISSUE THREAD

**Issue by axel7born** [cloudfoundry/routing-release#262]
## Issue
Uneven load balancing when using a route-service.

## Affected Versions
since 0.226.0
https://github.com/cloudfoundry/gorouter/commit/039ab0c6f93f13d2fcb4abb30f29c2c17842ee1b

## Context

We noticed an uneven load balancing in an app using a route-service since the above mentioned change.
In our a scenario it is quite common to have 4xx responses, which are not caused by stale routes.
This results in pruning the the endpoint at index 0.
The endpoint is added a least 20 s later.
However, the code that deletes the endpoint  at index 0 in the pool, replaces it by the last value in the array.
So, the last element that came in, is the first that will be deleted again.
As this happens very often in our scenario, this results in an uneven distribution of pruned instances and as result in an uneven load distribution, as some instances are removed more often from the pool than others.
https://github.com/cloudfoundry/gorouter/blob/7a51f240745a5f860e50b00b96d1f91a595dc001/route/pool.go#L360

The uneven load distribution led to overloaded instances.
We noticed the huge amount of `endpoint-registered` log messages from the gorouter.
Unfortunately, there is no log message for pruned endpoints in this case.
https://github.com/cloudfoundry/gorouter/blob/7a51f240745a5f860e50b00b96d1f91a595dc001/handlers/routeservice.go#L151

## Steps to Reproduce

Set-up the scenario described above.

## Expected result

Load distribution should be even, also in case of route-services and 4xx status codes.

## Possible Fix

Provide a special case for deleting an endpoint at index 0:
```
es[0], es = nil, es[1:]
```
This way, there would be a round-robin for pruned instances and the load would be evenly distributed. 
However, we did not test this.
Debugging would have been easier with a log message when pruning endpoints for route-services.

**Comment by geofffranks** [comment]
What 4xx messages are your routeservices returning in this case? We have seen issues where route-service URLs contain auth information, and become out of date.

I'm trying to determine whether this should be fixed just by addressing the uneven load balancing + adding more logging, or if we should rethink how we're detecting stale routes to be pruned.

**Comment by iromanko-sap** [comment]
Hi,
this is the distribution of 4xx requests and its codes for a timeframe of 15 min.
429 is is our rate-limiting
404 can happen due to a pruned tenant - which is ok from our side
401 & 403 are also pretty common since our service is doing authorization & authentication.
![2022-03-07_08-16-15](https://user-images.githubusercontent.com/101089895/156986477-e22c7cb4-e7c0-407b-b542-e686699096e6.png)

**Comment by geofffranks** [comment]
Interesting. In the case of a 401/403, the authentication is handled client-side rather than in the route-service definition, correct? 

When you receive 404s, is there anything that needs to change on the route service configuration in CF to make things work again, or is all the configuration aside from the URL handled separately from CF?

Lastly, is this a fully-brokered, static-brokered, or user-provided route service? I'm assuming probably fully-brokered based on the context, but just double checking.

**Comment by iromanko-sap** [comment]
@geofffranks correct, the authn is handled by other service which is behind the route service. 
If we receive 404 it can basically mean the following: 
1) someone is calling a non-existent tenant (can be deleted in the meantime or it never existed which would mean typo or human error)
2) our service is in a weird state and is showing 404 instead of 500, which is normally never the case.
Basically in both scenarios nothing has to be changed in the configuration of our route service. It should just reroute the traffic as usual to our business application.
3) Our scenario is the User-Provided Service.

**Comment by iromanko-sap** [comment]
Hi @geofffranks,
is there any progress regarding the issue or do you need any further information from us?

**Comment by geofffranks** [comment]
I was actually working on some possible fixes for this yesterday.  We're looking at options that don't involve pruning endpoints based off of route-services responses.

I don't think any additional info is needed at this time

**Comment by iromanko-sap** [comment]
@geofffranks, great! I am happy that this issue is going forward.

**Comment by geofffranks** [comment]
FYI @iromanko-sap @axel7born take a look at the gorouter#315 PR linked ^^ as a possible fix for this

(don't prune routes in this scenario in the first place then)

**Comment by geofffranks** [comment]
I'm going to close this, now that 0.232.0 is out. It reverts all of the logic that caused this problem for you, so that should be fixed. 

If you're still having issues, feel free to re-open!

**Comment by axel7born** [comment]
@geofffranks Thanks for fixing!

**Comment by iromanko-sap** [comment]
@geofffranks Huge thanks! I am eager to see it on our landscapes!
