### ISSUE TITLE
Improve load balancing across availability zones using tags

### ISSUE THREAD

**Issue by domdom82** [cloudfoundry/routing-release#292]
## Issue
This is another facet of issue #285 

- In an AZ outage scenario a whole set of endpoints may no longer be operational.
- Even if there are multiple endpoints available in multiple AZs, gorouter will not know about them as endpoints have no AZ metadata assigned to them
- If the endpoint list happens to have 3 endpoints from a broken AZ in order, the request will fail despite retries

## Affected Versions
All

## Context

During a "chaos day" testing where we deliberately shut down one AZ, we saw 502 errors going into CC that were retried but failed eventually because all tried endpoints happened to be in the same (broken) AZ.

In our case we had 117 endpoints registered for the route "api.cf.mycloud.com/networking" (pulled from /routes of a gorouter)
```
[
  {
    "address": "10.0.129.88:4002",
    "protocol": "http1",
    "tls": true,
    "ttl": 120,
    "tags": null,
    "private_instance_id": "6ccdc49f-9d35-499d-64a5-a1d85af4c809",
    "server_cert_domain_san": "api.cf.mycloud.com"
  },
  {
    "address": "10.0.129.188:4002",
    "protocol": "http1",
    "tls": true,
    "ttl": 120,
    "tags": null,
    "private_instance_id": "06dc3a7f-95fb-4386-7d8d-0d7687fd763f",
    "server_cert_domain_san": "api.cf.mycloud.com"
  },
  {
    "address": "10.0.129.108:4002",
    "protocol": "http1",
    "tls": true,
    "ttl": 120,
    "tags": null,
    "private_instance_id": "89267059-8d0c-48f1-5d43-9585bea92daa",
    "server_cert_domain_san": "api.cf.mycloud.com"
  },
  {
    "address": "10.0.129.179:4002",
    "protocol": "http1",
    "tls": true,
    "ttl": 120,
    "tags": null,
    "private_instance_id": "b28c76e8-155f-43b9-4bf2-59eada25adf1",
    "server_cert_domain_san": "api.cf.mycloud.com"
  },
  {
    "address": "10.0.129.177:4002",
    "protocol": "http1",
    "tls": true,
    "ttl": 120,
    "tags": null,
    "private_instance_id": "97008758-27a8-4d4e-4773-318b5bccea0c",
    "server_cert_domain_san": "api.cf.mycloud.com"
  },
  {
    "address": "10.0.129.116:4002",
    "protocol": "http1",
    "tls": true,
    "ttl": 120,
    "tags": null,
    "private_instance_id": "71186764-9ce2-4d11-5dc4-1f6611d731dd",
    "server_cert_domain_san": "api.cf.mycloud.com"
  },
  {
    "address": "10.0.65.102:4002",
    "protocol": "http1",
    "tls": true,
    "ttl": 120,
    "tags": null,
    "private_instance_id": "00241ad3-a36d-4fe3-470f-773ee65a8630",
    "server_cert_domain_san": "api.cf.mycloud.com"
  },

(...)
```

Gorouter stopped after the third endpoint and issued a 502. The first endpoint in another AZ would have been endpoint number 7 in the list. 

The problem with just adding more retries is that all errors we saw were
```
dial tcp <ip>:4002: i/o timeout
```
so with the default setting, every retry adds another 5s to the total request time, and most clients (in this case, the CF CLI)
will just give up after e.g. 15s and don't wait until gorouter successfully tried an endpoint after, like 2 minutes or so.

## Steps to Reproduce

1. Set up a local gorouter
2. Inject a route with 4 endpoints, three of them in AZ1 not working, one of them in AZ2 working
3. Curl the route with GET

## Expected result

Gorouter tries another AZ after the first failed attempt and returns 200 OK.

## Current result

Gorouter tries 3 times the same AZ and fails, returning 502 endpoint_failed

## Possible Fix

Looking at the "tags" field in a route table entry, for route-registrar entries it looks like this:
```
  {
    "address": "10.0.65.102:4002",
    "protocol": "http1",
    "tls": true,
    "ttl": 120,
    "tags": null,
    "private_instance_id": "00241ad3-a36d-4fe3-470f-773ee65a8630",
    "server_cert_domain_san": "api.cf.mycloud.com"
  }
```
for CF apps it looks like this:
```
{
  "address": "10.0.73.1:61012",
  "protocol": "http1",
  "tls": true,
  "ttl": 120,
  "tags": {
    "app_id": "1f7492ad-4e9c-41eb-9f1a-29ebf9265d6c",
    "app_name": "my-app",
    "component": "route-emitter",
    "instance_id": "0",
    "organization_id": "bc578e33-bce1-4bce-91c3-a302bcb27ee3",
    "organization_name": "my-Org",
    "process_id": "b5aca3a5-d49e-441f-b3c1-9b4f028a77d1",
    "process_instance_id": "c4186ae3-14e3-4e30-7c2e-b587",
    "process_type": "web",
    "source_id": "1f7492ad-4e9c-41eb-9f1a-29ebf9265d6c",
    "space_id": "442f1c44-3f4b-4db8-a964-4a74d8e044bf",
    "space_name": "my-Space"
  },
  "private_instance_id": "c4186ae3-14e3-4e30-7c2e-b587",
  "server_cert_domain_san": "c4186ae3-14e3-4e30-7c2e-b587"
}
```

if the entries looked like this:
```
  {
    "address": "10.0.65.102:4002",
    "protocol": "http1",
    "tls": true,
    "ttl": 120,
    "tags": {
       "az": "z1"
      },
    "private_instance_id": "00241ad3-a36d-4fe3-470f-773ee65a8630",
    "server_cert_domain_san": "api.cf.mycloud.com"
  }
```
for CF apps it looks like this:
```
{
  "address": "10.0.73.1:61012",
  "protocol": "http1",
  "tls": true,
  "ttl": 120,
  "tags": {
    "az": "z1"
    "app_id": "1f7492ad-4e9c-41eb-9f1a-29ebf9265d6c",
    "app_name": "my-app",
    "component": "route-emitter",
    "instance_id": "0",
    "organization_id": "bc578e33-bce1-4bce-91c3-a302bcb27ee3",
    "organization_name": "my-Org",
    "process_id": "b5aca3a5-d49e-441f-b3c1-9b4f028a77d1",
    "process_instance_id": "c4186ae3-14e3-4e30-7c2e-b587",
    "process_type": "web",
    "source_id": "1f7492ad-4e9c-41eb-9f1a-29ebf9265d6c",
    "space_id": "442f1c44-3f4b-4db8-a964-4a74d8e044bf",
    "space_name": "my-Space"
  },
  "private_instance_id": "c4186ae3-14e3-4e30-7c2e-b587",
  "server_cert_domain_san": "c4186ae3-14e3-4e30-7c2e-b587"
}
```

then gorouter would have the option to be smarter about retries and use the "az" tag to select a different AZ on the next attempt.

To my knowledge this would require changes in:

- route-emitter
- route-registrar
- gorouter

So it's not a small thing to do. However, we could lay down the foundation of this by adding functionality in the load balancing algorithms (round-robin, least-connection) to defensively check if such tags exist. If they don't we just skip and go along as usual. If they do exist, we take them into account and try to find an endpoint in a different AZ than last time.

**Comment by ameowlia** [comment]
👋 Hi @domdom82 , 

Thanks for writing this up. This sounds like a great idea. LMK if you need any pointers for where changes need to be made. I suggest trying to make multiple small PRs rather than one big PR. Maybe one PR to add az tags to route registrar endpoints. One PR to add azs to app endpoints. And one PR to have gorouter respect those az tags.

**Comment by katter** [comment]
This could as well come in handy for adding a LB algorithm that helps avoiding zone traversal (if possible). Inter-Zone egress cost can be quite hurting in larger deployments

**Comment by ameowlia** [comment]
I think adding this functionality to do exactly what @domdom82 suggests where gorouter takes AZ into account _when retrying a failed endpoint_, is a good idea that poses little risk.

However, I want to depart from that topic and talk about what @katter brought up, which is using az-aware routing that helps avoid zone traversal and reduce latency. In general, I think this is a great idea, but I think if done incorrectly it could pose a lot of risks.

### Risky Example
**Setup**
* There are 3 gorouters. Two in AZ-1, one in AZ-2.
* Each gorouter defaults to sending traffic to app’s in its own AZ.
* There are 3 app instances. One in AZ-1, two in AZ-2. 
* There are 1,002 requests.
* Each gorouter will get 33% of each request. 334 requests per gorouter.
* The gorouters in AZ-1 will send all of their traffic to the app in AZ-1. This app will get 668 requests. ~66% of the traffic.
* The gorouter in AZ-2 will round robin between the two apps in AZ-2. Each app will get 167 requests, ~16% of the total traffic.
* **Result: one app instance gets ~66% of the traffic, more than 4 times the amount of the other apps.**
* I think this traffic pattern change is dangerous. It could crash apps. I think it would be hard for app devs to diagnose the issue, and hard (or impossible) for them to fix the issue.

![image](https://user-images.githubusercontent.com/7025605/208478544-65347975-fce6-4c80-9619-4858c5001cfb.png)

### A possible solution
In order to de-risk the above situation, I think app devs in to be able to understand and control app distribution across AZs.

Imagine the following...
* An operator deploys multiple isolation segments (Diego Cells and Routers).
* Each isolation segment is only in one AZ. 
* App devs can opt-in to AZ based routing on an app-by-app basis. [This would be a new feature.]
* App devs can deploy the same app, with the same route, across all isolation segments. [This would be a new feature.]
* App devs can discover via the CLI and Apps Manager which isolation segment and AZ their apps are in. [This would be a new feature.]
* App devs can scale their apps in different isolation segments independently. [This would be a new feature.]
* The gorouters in each segment will default to sending traffic to its own AZ, but can fall back to other AZs. [This would be a new feature.]

💸 As you can see, the above proposal would take _a lot_ of work. But I can't think of a different _safe_ way to implement this. Ultimately it is up to product people to decide if the cost of this is worth it. 

😄 Thanks for following my digression.

**Comment by domdom82** [comment]
@ameowlia thanks for your in-depth analysis 😄 
Since gorouter doesn't know about other gorouters but it does know its world-view about what apps exist, one solution to your "risky" scenario could be to only make gorouter prefer the local AZ if the number of app instances in that zone is greater or equal to the total number of instances over number of zones, e.g.

```
use_local(gorouter) = nr_local_apps >= ceil(nr_apps / nr_zones)
```

in your example:
```
nr_apps = 3
nr_zones = 2
ceil(nr_apps / nr_zones) = ceil(1.5) = 2

use_local(g1) = false
use_local(g2) = false
use_local(g3) = true
```

this applies in all cases where the number of apps can't be divided cleanly by the number of zones. 
e.g. 4 apps in 3 zones = 1.3 => need at least 2 in local zone

**Comment by katter** [comment]
@ameowlia Thanks for your write-up. I must say that in a deployment of a size where this issue is relevant, I wouldn't bother with zone traversal of packets. In a larger environment, with evenly deployed gorouters and cells and app deployments that are in the two digit area, handling 1000s of rps probability should take us on the safe side.
In general this would be a "you know what you're doing" setting. Like altering the CPU quota or Memory overcommit for Diego and such.

**Comment by domdom82** [comment]
Closing in favor of #356
