### ISSUE TITLE
Regression for local testing of Routing Release

### ISSUE THREAD

**Issue by peanball** [cloudfoundry/routing-release#352]
No

## Issue

Local testing via Docker is not possible because of hardcoded paths.

Scripts introduced with https://github.com/cloudfoundry/routing-release/pull/334 / moved with #349.

## Affected Versions

main / not affecting the release, just the developer experience.

## Traffic Diagram 

 
N/A

## Steps to Reproduce

call `scripts/test-in-docker-locally`.

## Expected result

The unit tests for all routing-release components are executed.

## Current result

The script fails with an undefined `REPO_NAME`. 

When that is provided, it fails with a missing `REPO_PATH`. 

When that is provided it fails in `build-binaries.bash` when trying to call the hardcoded path `/ci/shared/helpers/extract-default-params-for-task.bash`, which will not exist on a developer's machine.

## Possible Fix

Adjust the scripts in a way that they can be used locally again.

**Comment by peanball** [comment]
@winkingturtle-vmw, the previous set of scripts supported launching a Docker container and running the tests there, also from MacOS.


I don't know if it was intended or not with this change to force only Linux to be able to execute tests at all.

**Comment by winkingturtle-vmw** [comment]
@peanball I believe README has been updated to reflect that `wg-app-platform-runtime-ci` would be required in order to run tests locally for routing-release. `REPO_*` comes from [.envrc](https://github.com/cloudfoundry/routing-release/blob/develop/.envrc) and [direnv](https://direnv.net/) we've always relied having that installed across many releases (maybe wasn't required before), but I see that README has no reference of direnv. I can update README to ensure installation of direnv is listed. Running tests are now only supported via docker and concourse only. When you have cloned `wg-app-platform-runtime-ci` next to routing-release and other runtime releases with `direnv` you should be able to just run `./scripts/test-in-docker-locally` in run all of tests and linters. 

The reason for this work is so that every runtime release to be tested in the same way instead of having different implementations across releases.

**Comment by peanball** [comment]
Hi @winkingturtle-vmw,

yes, `direnv` was not required. I had found that while browsing after opening the issue. It would be good if you could document that. 

A quick reminder link for the prerequisites (i.e. cloning the CI repo) next to "how to run this stuff locally" would also be appreciated. It's this particular section [that is linked in e.g. the PR template](https://github.com/cloudfoundry/routing-release/blob/df1081d48007dbf07af597ba97f9a22b539f5ced/PULL_REQUEST_TEMPLATE.md?plain=1#L33), but it's not obvious that there are (new for now) prerequisites that need to be taken into account before you can follow the instructions in that section.

I appreciate the consolidation work. It just caught me 'off guard' as I was preparing to submit a PR, rebased everything and suddenly the tests are not working. Reading the updated docs helped somewhat but didn't show the full picture. And here we are :-)

**Comment by peanball** [comment]
Final note: supposedly I have `direnv` enabled and active via zsh4humans, but somehow it will not pick up the `.envrc` in the routing-release repo. That said, a simple `source .envrc` works fine as well. Maybe an alternative worth mentioning for people that don't have / don't want `direnv`?

**Comment by winkingturtle-vmw** [comment]
Thanks for feedback, I've submitted a PR with the proposed changed.

>  That said, a simple source .envrc works fine as well

While it's possible, it's actually not recommend to `source` the file. That's because we use `REPO_PATH` and `REPO_NAME` identifiers to run tests when someone changes directory from routing-release to nats-release for example. Those env variables helps with creating/mounting/running docker containers. With `direnv` when you go away from that directory, the exported variable is then removed and helps prevent mounting and creating incorrect containers.

**Comment by winkingturtle-vmw** [comment]
@peanball I've gone ahead and updated the PR to remove dependency on `direnv` and `.envrc`. I hope that resolves some of the questions you'd raised.
