### ISSUE TITLE
Error message on invalid app index is wrong

### ISSUE THREAD

**Issue by jkugler** [cloudfoundry/routing-release#72]
## Issue

Error message on invalid app index is wrong.

## Context

Giving an invalid app index returns a 404 with "Not Found: Requested route ('URL to apps') does not exist."

## Steps to Reproduce

Make a request to an app with X-CF-APP-INSTANCE: APP_GUID:APP_INDEX.  (Per the docs here: http://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#surgical-routing)  x

## Expected result

Error message should say "requested instance does not exist).

## Current result

If the app index is invalid, instead of returning a message saying so, you can an error message that says the request route (i.e. the URL) does not exist.  

## Possible Fix

Fix the error message. :)

## `name of issue` Output Results

N/A

**Comment by shashwathi** [comment]
Hi @jkugler : 

`404` HTTP status code represents the requested resource does not exist. In this instance when request is made to an app with `X-CF-APP-INSTANCE` header and `APP_INDEX` does not exist, it is valid to throw `404` with message `Requested route ('URL to apps') does not exist`. 

I am not inclined to throw `Requested instance does not exist` message because somebody can curl the application GUID with different indices and get the total number of instances. Throwing generic error about resource missing is always preferred over throwing error with what resource is missing. 

Eg: If you enter password or username wrong, it is not recommended to error with message `Password is incorrect` or `Username is incorrect`

Regards
Shash

**Comment by jkugler** [comment]
If you know the GUID, wouldn't you already be in a position to obtain information about the app, including number of instances?

I wasn't debating the error code returned (404, as yes, it is not found), but the message.  Returning a message of "requested route...does not exist" is very misleading, and confusing when you are trying to debug an issue. When I was working with the X-CF-APP-INSTANCE header, I kept getting the "invalid route" message, and could not figure out why I was getting that message, as I was using the URL/route provided to me by cf metadata. The message should be clearer as to what the actual error is. You're right about that you should specify about password or username is incorrect, but in this case, it's not a security issue, and the message should allow the developer to determine what actually failed, not point to an issue that will ultimately lead the developer down the wrong path.

**Comment by shashwathi** [comment]
@jkugler : 

> If you know the GUID, wouldn't you already be in a position to obtain information about the app, including number of instances?

If you have access to the org and space, then you will have access to app metadata otherwise no.

> I was working with the X-CF-APP-INSTANCE header, I kept getting the "invalid route" message, and could not figure out why I was getting that message

I see your point in offering better debugging interface for app developers. @shalako any thoughts or concerns about this request?

Note: We could also improve the logging on gorouter to print better error msg if route is not found because of non-existent index.We should do this either way.

Regards
Shash

**Comment by adobley** [comment]
Hi @jkugler,

Given the age of this issue and that we are focusing our efforts on envoy at this time, is this still something that you see value in addressing? Since this is an older issue, we will close it for now. Please feel welcome to reopen it if you have anything further.

Thanks!

**Comment by jkugler** [comment]
Yes, I still like to see better debugging messages. :)

**Comment by adobley** [comment]
It is unlikely that we will prioritize adding this feature before integrating Istio/Envoy since that is a higher priority for us and will replace gorouter. We will gladly review a PR however. I'm sorry that we are unable to give this more attention.
